<a href="https://colab.research.google.com/github/fabrizio-lanzetti/Preprocesamiento-de-datos/blob/main/encuesta_preprocesamiento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Procesamiento de datos "ENCUESTA ESTUDIANTIL"

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv(r"C:\Users\fabri\OneDrive\Desktop\Nueva carpeta\encuestra_instituto.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 45 columns):
 #   Column                                                                                                                                                                              Non-Null Count  Dtype
---  ------                                                                                                                                                                              --------------  -----
 0   Marca temporal                                                                                                                                                                      214 non-null    object
 1   Género (registrado al nacer)                                                                                                                                                        214 non-null    object
 2   ¿Cómo te consideras/autopercibes?                                                                                                                                                   214 non-null    object
 3   Nacionalidad                                                                                                                                                                        214 non-null    object
 4   ¿Te reconoces/consideras indígena o descendiente de pueblos originarios?                                                                                                            210 non-null    object
 5   Edad (en números)                                                                                                                                                                   212 non-null    float64
 6   Estado civil                                                                                                                                                                        213 non-null    object
 7   Localidad de residencia durante el año académico                                                                                                                                    214 non-null    object
 8   ¿Realizás alguna actividad física o deporte regularmente?                                                                                                                           214 non-null    object
 9   ¿Tienes alguna condición, dificultad o limitación que requiera adaptaciones pedagógicas o edilicias?                                                                                213 non-null    object
 10  ¿Padeces ansiedad, depresión u otra afección mental?                                                                                                                                214 non-null    object
 11  ¿A qué distancia se encuentra el lugar donde residís del Instituto?                                                                                                                 212 non-null    object
 12  ¿Qué medio de transporte utilizás habitualmente para llegar al Instituto?                                                                                                           214 non-null    object
 13  ¿Cuánto tiempo en promedio te toma llegar de tu domicilio al Instituto?                                                                                                             214 non-null    object
 14  ¿Cómo financias tus gastos de movilidad?                                                                                                                                            213 non-null    object
 15  ¿Trabajás?                                                                                                                                                                          214 non-null    object
 16  En tu trabajo te desempeñás como... (en caso de tener más de un trabajo responder en base al que te reporte mayor ingreso)                                                          93 non-null     object
 17  ¿A qué te dedicás?                                                                                                                                                                  91 non-null     object
 18  ¿Dispones de cobertura de obra social por tu trabajo?                                                                                                                               96 non-null     object
 19  ¿Cuántas horas trabajás semanalmente?                                                                                                                                               93 non-null     object
 20  Tus horarios son:                                                                                                                                                                   94 non-null     object
 21  ¿Disponés de alguna beca para financiar tus estudios?                                                                                                                               212 non-null    object
 22  Carrera/as en las que estás inscripto/a                                                                                                                                             213 non-null    object
 23  Año en que ingresaste a la carrera. (Ej. Si este es tu primer año contestar 2024)                                                                                                   213 non-null    float64
 24  Estás inscripto/a para cursar espacios correspondientes ¿a qué año del diseño curricular?                                                                                           209 non-null    object
 25  Cantidad de miembros de tu hogar de residencia (en números)                                                                                                                         211 non-null    float64
 26  Cantidad de hijo/as                                                                                                                                                                 210 non-null    object
 27  Máximo nivel educativo del padre                                                                                                                                                    209 non-null    object
 28  Máximo nivel educativo de la madre                                                                                                                                                  211 non-null    object
 29  ¿En qué año egresaste de la escuela secundaria?                                                                                                                                     214 non-null    int64
 30  La escuela secundaria de la que egresaste es de gestión:                                                                                                                            214 non-null    object
 31  ¿Cursaste otra carrera antes de este año?                                                                                                                                           214 non-null    object
 32  ¿Qué carrera/s cursaste previamente? (Si es más de una, responder por la más reciente)                                                                                              70 non-null     object
 33  ¿En qué institución realizaste esos estudios?                                                                                                                                       69 non-null     object
 34  ¿Completaste tus estudios?                                                                                                                                                          70 non-null     object
 35  ¿Cuáles son los medios tecnológicos de los que disponés para tus estudios?                                                                                                          214 non-null    object
 36  Los dispositivos que utilizás son:                                                                                                                                                  214 non-null    object
 37  ¿Con qué posibilidades de conectividad contás?                                                                                                                                      214 non-null    object
 38  ¿Desde dónde te conectás a wi fi habitualmente?                                                                                                                                     214 non-null    object
 39  ¿Qué calidad considerás que tiene tu conexión?                                                                                                                                      214 non-null    object
 40  ¿Considerás que te sería posible cursar materias en el turno mañana?                                                                                                                214 non-null    object
 41  ¿Considerás que una modificación en el horario de funcionamiento del Instituto durante este año (comenzando las clases desde el turno mañana) dificultaría tu asistencia al mismo?  214 non-null    object
 42  ¿Cuáles considerás que serían las principales dificultades para tu asistencia durante el turno matutino?                                                                            99 non-null     object
 43  Para cerrar el relevamiento nos interesaría conocer cuáles son, desde tu punto de vista, los principales problemas o aspectos a mejorar en nuestra institución                      129 non-null    object
 44  ¿Hay algo más que quieras agregar, que pueda mejorar esta encuesta?                                                                                                                 70 non-null     object
dtypes: float64(3), int64(1), object(41)
memory usage: 75.4+ KB

In [ ]:
df1 = df.iloc[:, :22]
df2 = df.iloc[:,22:46]

# Vamos a dividir el dataframe en 2 partes para trabajar mas comodos

## Columnas Originales y Nuevas Editadas del df1

| **#** | **Columna Original**                                                                                             | **Columna Editada**                              |
|-------|-------------------------------------------------------------------------------------------------------------------|--------------------------------------------------|
| 0     | Marca temporal                                                                                                     | Marca_Temporal                                  |                              |
| 1     | Género (registrado al nacer)                                                                                       | Genero_Nacer                                    |
| 2     | ¿Cómo te consideras/autopercibes?                                                                                  | Autopercepcion                                   |
| 3     | Nacionalidad                                                                                                       | Nacionalidad                                    |
| 4     | ¿Te reconoces/consideras indígena o descendiente de pueblos originarios?                                           | Indigena_O_Descendiente                         |
| 5     | Edad (en números)                                                                                                  | Edad                                            |
| 6     | Estado civil                                                                                                       | Estado_Civil                                    |
| 7     | Localidad de residencia durante el año académico                                                                   | Localidad_Residencia                            |
| 8     | ¿Realizás alguna actividad física o deporte regularmente?                                                          | Actividad_Fisica                                |
| 9    | ¿Tienes alguna condición, dificultad o limitación que requiera adaptaciones pedagógicas o edilicias?               | Condiciones_Limitaciones                        |
| 10    | ¿Padeces ansiedad, depresión u otra afección mental?                                                                | Afecciones_Mentales                             |
| 11    | ¿A qué distancia se encuentra el lugar donde residís del Instituto?                                                | Distancia_Instituto                             |
| 12    | ¿Qué medio de transporte utilizás habitualmente para llegar al Instituto?                                          | Medio_Transporte                                |
| 13    | ¿Cuánto tiempo en promedio te toma llegar de tu domicilio al Instituto?                                            | Tiempo_Traslado                                  |
| 14    | ¿Cómo financias tus gastos de movilidad?                                                                             | Financiamiento_Movilidad                        |
| 15    | ¿Trabajás?                                                                                                         | Trabajas                                         |
| 16    | En tu trabajo te desempeñás como... (en caso de tener más de un trabajo responder en base al que te reporte mayor ingreso) | Desempeno_Laboral                                |
| 17    | ¿A qué te dedicás?                                                                                                 | Actividad_Profesional                           |
| 18    | ¿Dispones de cobertura de obra social por tu trabajo?                                                              | Obra_Social_Trabajo                             |
| 19    | ¿Cuántas horas trabajás semanalmente?                                                                              | Horas_Trabajo                                   |
| 20    | Tus horarios son:                                                                                                  | Horarios_Trabajo                                 |
| 21    | ¿Disponés de alguna beca para financiar tus estudios?                                                              | Beca_Estudios                                    |

In [ ]:
columnas_reemplazo = {
    'Marca temporal': 'Marca_Temporal',
    'Dirección de correo electrónico': 'Correo_Electronico',
    'Género (registrado al nacer)': 'Genero_Nacer',
    '¿Cómo te consideras/autopercibes?': 'Autopercepcion',
    'Nacionalidad': 'Nacionalidad',
    '¿Te reconoces/consideras indígena o descendiente de pueblos originarios?': 'Indigena_O_Descendiente',
    'Edad (en números)': 'Edad',
    'Estado civil': 'Estado_Civil',
    'Localidad de residencia durante el año académico': 'Localidad_Residencia',
    '¿Realizás alguna actividad física o deporte regularmente?': 'Actividad_Fisica',
    '¿Tienes alguna condición, dificultad o limitación que requiera adaptaciones pedagógicas o edilicias?': 'Condiciones_Limitaciones',
    '¿Padeces ansiedad, depresión u otra afección mental?': 'Afecciones_Mentales',
    '¿A qué distancia se encuentra el lugar donde residís del Instituto?': 'Distancia_Instituto',
    '¿Qué medio de transporte utilizás habitualmente para llegar al Instituto?': 'Medio_Transporte',
    '¿Cuánto tiempo en promedio te toma llegar de tu domicilio al Instituto?': 'Tiempo_Traslado',
    '¿Cómo financias tus gastos de movilidad?': 'Financiamiento_Movilidad',
    '¿Trabajás?': 'Trabajas',
    'En tu trabajo te desempeñás como... (en caso de tener más de un trabajo responder en base al que te reporte mayor ingreso)': 'Desempeno_Laboral',
    '¿A qué te dedicás?': 'Actividad_Profesional',
    '¿Dispones de cobertura de obra social por tu trabajo?': 'Obra_Social_Trabajo',
    '¿Cuántas horas trabajás semanalmente?': 'Horas_Trabajo',
    'Tus horarios son:': 'Horarios_Trabajo',
    '¿Disponés de alguna beca para financiar tus estudios?': 'Beca_Estudios'
}

df1.rename(columns=columnas_reemplazo, inplace=True)


df1.head()

,Marca_Temporal,Genero_Nacer,Autopercepcion,Nacionalidad,Indigena_O_Descendiente,Edad,Estado_Civil,Localidad_Residencia,Actividad_Fisica,Condiciones_Limitaciones,...,Medio_Transporte,Tiempo_Traslado,Financiamiento_Movilidad,Trabajas,Desempeno_Laboral,Actividad_Profesional,Obra_Social_Trabajo,Horas_Trabajo,Horarios_Trabajo,Beca_Estudios
0,2024-05-29 09:34:28.466,Mujer / Femenino,Mujer,Argentino/a,No,27.0,Soltero/a,Barrancas,No,No,...,Colectivo,Entre 30 minutos y 1 hora,Boleto Educativo Gratuito,Sí,Empleado en relación de dependencia,Empleada doméstica,No,de 10 a 20 hs semanales,Fijos,PROGRESAR
1,2024-05-29 09:35:20.150,Mujer / Femenino,Mujer,Argentino/a,No,18.0,Soltero/a,Larrechea,No,No,...,Auto,Menos de 30 minutos,Ingresos propios,No,NaN,NaN,NaN,NaN,NaN,PROGRESAR
2,2024-05-29 09:38:48.713,Mujer / Femenino,Mujer,Argentino/a,No,20.0,Soltero/a,Caima,"Sí, al menos una vez por semana",No,...,Colectivo,Entre 1 y 2 horas,Boleto Educativo Gratuito,No,NaN,NaN,NaN,NaN,NaN,PROGRESAR
3,2024-05-29 09:41:36.380,Mujer / Femenino,Mujer,Argentino/a,No,18.0,NaN,Sauce Viejo,"Sí, al menos una vez por semana",No,...,Colectivo,Menos de 30 minutos,Boleto Educativo Gratuito,No,NaN,NaN,NaN,NaN,NaN,No cuento con ninguna beca
4,2024-05-29 09:46:56.746,Mujer / Femenino,Mujer,Argentino/a,No,21.0,En pareja/Unión de hecho,Coronda,No,No,...,Caminando,Menos de 30 minutos,No tengo gastos de movilidad,No,NaN,NaN,NaN,NaN,NaN,PROGRESAR

# Columnas Originales y Nuevas Editadas del df2

| **#** | **Columna Original**                                                                                             | **Columna Editada**                               |
|-------|-------------------------------------------------------------------------------------------------------------------|---------------------------------------------------|
| 0     | Carrera/as en las que estás inscripto/a                                                                            | Carreras_Inscripcion                             |
| 1     | Año en que ingresaste a la carrera. (Ej. Si este es tu primer año contestar 2024)                                  | Ano_Ingreso_Carrera                              |
| 2     | Estás inscripto/a para cursar espacios correspondientes ¿a qué año del diseño curricular?                         | Ano_Curricular                                    |
| 3     | Cantidad de miembros de tu hogar de residencia (en números)                                                        | Miembros_Hogar                                    |
| 4     | Cantidad de hijo/as                                                                                                 | Cantidad_Hijos                                    |
| 5     | Máximo nivel educativo del padre                                                                                    | Nivel_Educativo_Padre                            |
| 6     | Máximo nivel educativo de la madre                                                                                  | Nivel_Educativo_Madre                            |
| 7     | ¿En qué año egresaste de la escuela secundaria?                                                                    | Ano_Egreso_Secundaria                             |
| 8     | La escuela secundaria de la que egresaste es de gestión:                                                           | Gestion_Escuela                                   |
| 9     | ¿Cursaste otra carrera antes de este año?                                                                          | Cursaste_Otra_Carrera                            |
| 10    | ¿Qué carrera/s cursaste previamente? (Si es más de una, responder por la más reciente)                             | Carrera_Previa                                    |
| 11    | ¿En qué institución realizaste esos estudios?                                                                     | Institucion_Estudio                               |
| 12    | ¿Completaste tus estudios?                                                                                        | Estudios_Completados                              |
| 13    | ¿Cuáles son los medios tecnológicos de los que disponés para tus estudios?                                         | Medios_Tecnologicos_Estudios                      |
| 14    | Los dispositivos que utilizás son:                                                                                 | Dispositivos_Usados                               |
| 15    | ¿Con qué posibilidades de conectividad contás?                                                                     | Conectividad                                      |
| 16    | ¿Desde dónde te conectás a wi fi habitualmente?                                                                    | Conexión_Wifi                                     |
| 17    | ¿Qué calidad considerás que tiene tu conexión?                                                                     | Calidad_Conexion                                  |
| 18    | ¿Considerás que te sería posible cursar materias en el turno mañana?                                               | Cursar_Mañana                                     |
| 19    | ¿Considerás que una modificación en el horario de funcionamiento del Instituto durante este año dificultaría tu asistencia al mismo? | Modificacion_Horario_Instituto                    |
| 20    | ¿Cuáles considerás que serían las principales dificultades para tu asistencia durante el turno matutino?          | Dificultades_Turno_Matutino                       |
| 21    | Para cerrar el relevamiento nos interesaría conocer cuáles son, desde tu punto de vista, los principales problemas o aspectos a mejorar en nuestra institución | Problemas_Aspectos_Institucion                    |
| 22    | ¿Hay algo más que quieras agregar, que pueda mejorar esta encuesta?                                                | Sugerencias_Encuesta                              |

In [ ]:
# Diccionario con las columnas originales como claves y las nuevas como valores
columnas_reemplazo = {
    'Carrera/as en las que estás inscripto/a': 'Carreras_Inscripcion',
    'Año en que ingresaste a la carrera. (Ej. Si este es tu primer año contestar 2024)': 'Ano_Ingreso_Carrera',
    'Estás inscripto/a para cursar espacios correspondientes ¿a qué año del diseño curricular?': 'Ano_Curricular',
    'Cantidad de miembros de tu hogar de residencia (en números)': 'Miembros_Hogar',
    'Cantidad de hijo/as': 'Cantidad_Hijos',
    'Máximo nivel educativo del padre': 'Nivel_Educativo_Padre',
    'Máximo nivel educativo de la madre': 'Nivel_Educativo_Madre',
    '¿En qué año egresaste de la escuela secundaria?': 'Ano_Egreso_Secundaria',
    'La escuela secundaria de la que egresaste es de gestión:': 'Gestion_Escuela',
    '¿Cursaste otra carrera antes de este año?': 'Cursaste_Otra_Carrera',
    '¿Qué carrera/s cursaste previamente? (Si es más de una, responder por la más reciente)': 'Carrera_Previa',
    '¿En qué institución realizaste esos estudios?': 'Institucion_Estudio',
    '¿Completaste tus estudios?': 'Estudios_Completados',
    '¿Cuáles son los medios tecnológicos de los que disponés para tus estudios?': 'Medios_Tecnologicos_Estudios',
    'Los dispositivos que utilizás son:': 'Dispositivos_Usados',
    '¿Con qué posibilidades de conectividad contás?': 'Conectividad',
    '¿Desde dónde te conectás a wi fi habitualmente?': 'Conexión_Wifi',
    '¿Qué calidad considerás que tiene tu conexión?': 'Calidad_Conexion',
    '¿Considerás que te sería posible cursar materias en el turno mañana?': 'Cursar_Mañana',
    '¿Considerás que una modificación en el horario de funcionamiento del Instituto durante este año dificultaría tu asistencia al mismo?': 'Modificacion_Horario_Instituto',
    '¿Cuáles considerás que serían las principales dificultades para tu asistencia durante el turno matutino?': 'Dificultades_Turno_Matutino',
    'Para cerrar el relevamiento nos interesaría conocer cuáles son, desde tu punto de vista, los principales problemas o aspectos a mejorar en nuestra institución': 'Problemas_Aspectos_Institucion',
    '¿Hay algo más que quieras agregar, que pueda mejorar esta encuesta?': 'Sugerencias_Encuesta'
}

# Reemplaza las columnas en el DataFrame utilizando el diccionario
df2.rename(columns=columnas_reemplazo, inplace=True)

# Verifica los primeros registros para asegurarte de que los cambios fueron aplicados
print(df2.head())

         Carreras_Inscripcion  Ano_Ingreso_Carrera Ano_Curricular  \
0  Prof. en Educación Inicial               2022.0         3º año
1  Prof. en Educación Inicial               2024.0         1º año
2  Prof. en Educación Inicial               2024.0         1º año
3  Prof. en Educación Inicial               2024.0            NaN
4  Prof. en Educación Inicial               2024.0         1º año

   Miembros_Hogar Cantidad_Hijos  Nivel_Educativo_Padre  \
0             2.0              1    Primario Incompleto
1             4.0              0  Secundario Incompleto
2             1.0              0                  Ns/Nc
3             7.0              0  Secundario Incompleto
4             3.0              1  Secundario Incompleto

   Nivel_Educativo_Madre  Ano_Egreso_Secundaria Gestion_Escuela  \
0     Terciario Completo                   2015         Pública
1      Primario Completo                   2023         Pública
2                  Ns/Nc                   2017         Pública
3    Secundario Completo                   2022         Pública
4  Secundario Incompleto                   2022         Pública

  Cursaste_Otra_Carrera  ...  \
0                    No  ...
1                    No  ...
2                    Sí  ...
3                    Sí  ...
4                    No  ...

                       Medios_Tecnologicos_Estudios Dispositivos_Usados  \
0                                           Celular     De uso personal
1  Celular, Computadora portatil (Notebook/netbook)     De uso personal
2                                           Celular     De uso personal
3                                           Celular     De uso personal
4                                           Celular     De uso personal

                 Conectividad                              Conexión_Wifi  \
0                       Wi-Fi                                      Hogar
1  Red celular (datos), Wi-Fi                   Hogar, Escuela/Instituto
2         Red celular (datos)                                    Ninguno
3  Red celular (datos), Wi-Fi                                      Hogar
4  Red celular (datos), Wi-Fi  Hogar, Escuela/Instituto, Espacio público

  Calidad_Conexion Cursar_Mañana  \
0            Buena            No
1          Regular       Tal vez
2          Regular            Sí
3          Regular            Sí
4          Regular            Sí

  ¿Considerás que una modificación en el horario de funcionamiento del Instituto durante este año (comenzando las clases desde el turno mañana) dificultaría tu asistencia al mismo?  \
0                                                 Si
1                                                 Si
2                                                 No
3                                                 No
4                                                 No

                         Dificultades_Turno_Matutino  \
0                  Para trabajar / conseguir trabajo
1  De organización familiar, De transporte, Econó...
2                                                NaN
3                                                NaN
4                                                NaN

                      Problemas_Aspectos_Institucion  \
0  Si, avisar con anticipación la falta del docen...
1  el orden,la organización sobre las aulas, ya q...
2                                                  .
3                                                NaN
4  A mí punto de vista,cambiar el horario de ingr...

                                Sugerencias_Encuesta
0                                                NaN
1                                                 no
2                                                  .
3                                                NaN
4  Con respecto al anexo,no hay alguna pregunta,y...

[5 rows x 23 columns]

# Reemplzado de nulos para analisis df1

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Marca_Temporal            214 non-null    object
 1   Genero_Nacer              214 non-null    object
 2   Autopercepcion            214 non-null    object
 3   Nacionalidad              214 non-null    object
 4   Indigena_O_Descendiente   210 non-null    object
 5   Edad                      212 non-null    float64
 6   Estado_Civil              213 non-null    object
 7   Localidad_Residencia      214 non-null    object
 8   Actividad_Fisica          214 non-null    object
 9   Condiciones_Limitaciones  213 non-null    object
 10  Afecciones_Mentales       214 non-null    object
 11  Distancia_Instituto       212 non-null    object
 12  Medio_Transporte          214 non-null    object
 13  Tiempo_Traslado           214 non-null    object
 14  Financiamiento_Movilidad  213 non-null    object
 15  Trabajas                  214 non-null    object
 16  Desempeno_Laboral         93 non-null     object
 17  Actividad_Profesional     91 non-null     object
 18  Obra_Social_Trabajo       96 non-null     object
 19  Horas_Trabajo             93 non-null     object
 20  Horarios_Trabajo          94 non-null     object
 21  Beca_Estudios             212 non-null    object
dtypes: float64(1), object(21)
memory usage: 36.9+ KB

In [ ]:
df1.loc[df1["Trabajas"] == "Sí", "Desempeno_Laboral"] = df1.loc[df1["Trabajas"] == "Sí", "Desempeno_Laboral"].fillna("No aclara")

In [ ]:
df1["Desempeno_Laboral"] = df1["Desempeno_Laboral"].fillna("No trabaja")

In [ ]:
df1.loc[df1["Trabajas"] == "Sí", "Actividad_Profesional"] = df1.loc[df1["Trabajas"] == "Sí", "Actividad_Profesional"].fillna("No aclara")

In [ ]:
df1["Actividad_Profesional"] = df1["Actividad_Profesional"].fillna("No trabaja")

In [ ]:
df1.loc[df1["Trabajas"] == "Sí", "Obra_Social_Trabajo"] = df1.loc[df1["Trabajas"] == "Sí", "Obra_Social_Trabajo"].fillna("No tiene/No Aclara")

In [ ]:
df1["Obra_Social_Trabajo"] = df1["Obra_Social_Trabajo"].fillna("No trabaja")

In [ ]:
df1.loc[df1["Trabajas"] == "Sí", "Horas_Trabajo"] = df1.loc[df1["Trabajas"] == "Sí", "Horas_Trabajo"].fillna("No Aclara")

In [ ]:
df1["Horas_Trabajo"] = df1["Horas_Trabajo"].fillna("No trabaja")

In [ ]:
df1.loc[df1["Trabajas"] == "Sí", "Horarios_Trabajo"] = df1.loc[df1["Trabajas"] == "Sí", "Horarios_Trabajo"].fillna("No Aclara")

In [ ]:
df1["Horarios_Trabajo"] = df1["Horarios_Trabajo"].fillna("No trabaja")

In [ ]:
print("Moda Indigena_O_Descendiente: ",df1["Indigena_O_Descendiente"].mode())
print("Moda edad",df1["Edad"].mode())
print("Moda Distancia_instituto",df1["Distancia_Instituto"].mode())
print("Moda Financiamiento_Movilidad",df1["Financiamiento_Movilidad"].mode())
print("Moda Beca_Estudioos",df1["Beca_Estudios"].mode())

Moda Indigena_O_Descendiente:  0    No
Name: Indigena_O_Descendiente, dtype: object
Moda edad 0    18.0
Name: Edad, dtype: float64
Moda Distancia_instituto 0    0-10 kms.
Name: Distancia_Instituto, dtype: object
Moda Financiamiento_Movilidad 0    No tengo gastos de movilidad
Name: Financiamiento_Movilidad, dtype: object
Moda Beca_Estudioos 0    No cuento con ninguna beca
Name: Beca_Estudios, dtype: object

In [ ]:
df1["Indigena_O_Descendiente"] = df1["Indigena_O_Descendiente"].fillna("No")
df1["Estado_Civil"] = df1["Estado_Civil"].fillna("No aclara")
df1["Edad"] = df1["Edad"].fillna(18)
df1["Condiciones_Limitaciones"] = df1["Condiciones_Limitaciones"].fillna("No aclara")
df1["Distancia_Instituto"] = df1["Distancia_Instituto"].fillna("0-10 kms")
df1["Financiamiento_Movilidad"] = df1["Financiamiento_Movilidad"].fillna("No tengo gastos de movilidad")
df1["Beca_Estudios"] = df1["Beca_Estudios"].fillna("No cuento con ninguna beca")

In [ ]:
df1.head()

,Marca_Temporal,Genero_Nacer,Autopercepcion,Nacionalidad,Indigena_O_Descendiente,Edad,Estado_Civil,Localidad_Residencia,Actividad_Fisica,Condiciones_Limitaciones,...,Medio_Transporte,Tiempo_Traslado,Financiamiento_Movilidad,Trabajas,Desempeno_Laboral,Actividad_Profesional,Obra_Social_Trabajo,Horas_Trabajo,Horarios_Trabajo,Beca_Estudios
0,2024-05-29 09:34:28.466,Mujer / Femenino,Mujer,Argentino/a,No,27.0,Soltero/a,Barrancas,No,No,...,Colectivo,Entre 30 minutos y 1 hora,Boleto Educativo Gratuito,Sí,Empleado en relación de dependencia,Empleada doméstica,No,de 10 a 20 hs semanales,Fijos,PROGRESAR
1,2024-05-29 09:35:20.150,Mujer / Femenino,Mujer,Argentino/a,No,18.0,Soltero/a,Larrechea,No,No,...,Auto,Menos de 30 minutos,Ingresos propios,No,No trabaja,No trabaja,No trabaja,No trabaja,No trabaja,PROGRESAR
2,2024-05-29 09:38:48.713,Mujer / Femenino,Mujer,Argentino/a,No,20.0,Soltero/a,Caima,"Sí, al menos una vez por semana",No,...,Colectivo,Entre 1 y 2 horas,Boleto Educativo Gratuito,No,No trabaja,No trabaja,No trabaja,No trabaja,No trabaja,PROGRESAR
3,2024-05-29 09:41:36.380,Mujer / Femenino,Mujer,Argentino/a,No,18.0,No aclara,Sauce Viejo,"Sí, al menos una vez por semana",No,...,Colectivo,Menos de 30 minutos,Boleto Educativo Gratuito,No,No trabaja,No trabaja,No trabaja,No trabaja,No trabaja,No cuento con ninguna beca
4,2024-05-29 09:46:56.746,Mujer / Femenino,Mujer,Argentino/a,No,21.0,En pareja/Unión de hecho,Coronda,No,No,...,Caminando,Menos de 30 minutos,No tengo gastos de movilidad,No,No trabaja,No trabaja,No trabaja,No trabaja,No trabaja,PROGRESAR

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Marca_Temporal            214 non-null    object
 1   Genero_Nacer              214 non-null    object
 2   Autopercepcion            214 non-null    object
 3   Nacionalidad              214 non-null    object
 4   Indigena_O_Descendiente   214 non-null    object
 5   Edad                      214 non-null    float64
 6   Estado_Civil              214 non-null    object
 7   Localidad_Residencia      214 non-null    object
 8   Actividad_Fisica          214 non-null    object
 9   Condiciones_Limitaciones  214 non-null    object
 10  Afecciones_Mentales       214 non-null    object
 11  Distancia_Instituto       214 non-null    object
 12  Medio_Transporte          214 non-null    object
 13  Tiempo_Traslado           214 non-null    object
 14  Financiamiento_Movilidad  214 non-null    object
 15  Trabajas                  214 non-null    object
 16  Desempeno_Laboral         214 non-null    object
 17  Actividad_Profesional     214 non-null    object
 18  Obra_Social_Trabajo       214 non-null    object
 19  Horas_Trabajo             214 non-null    object
 20  Horarios_Trabajo          214 non-null    object
 21  Beca_Estudios             214 non-null    object
dtypes: float64(1), object(21)
memory usage: 36.9+ KB

### Ya tenemos toda la primer parte resuelta. Ahora vamos a exportar a csv

In [ ]:
df1.to_csv('encuestaP1.csv', index=False)

# Reemplzado de nulos para analisis df2

In [ ]:
df2.rename(columns={'¿Considerás que una modificación en el horario de funcionamiento del Instituto durante este año (comenzando las clases desde el turno mañana) dificultaría tu asistencia al mismo?': 'Modificacion_Horario_Instituto'}, inplace=True)

In [ ]:
df2.head(10)

,Carreras_Inscripcion,Ano_Ingreso_Carrera,Ano_Curricular,Miembros_Hogar,Cantidad_Hijos,Nivel_Educativo_Padre,Nivel_Educativo_Madre,Ano_Egreso_Secundaria,Gestion_Escuela,Cursaste_Otra_Carrera,...,Medios_Tecnologicos_Estudios,Dispositivos_Usados,Conectividad,Conexión_Wifi,Calidad_Conexion,Cursar_Mañana,Modificacion_Horario_Instituto,Dificultades_Turno_Matutino,Problemas_Aspectos_Institucion,Sugerencias_Encuesta
0,Prof. en Educación Inicial,2022.0,3º año,2.0,1,Primario Incompleto,Terciario Completo,2015,Pública,No,...,Celular,De uso personal,Wi-Fi,Hogar,Buena,No,Si,Para trabajar / conseguir trabajo,"Si, avisar con anticipación la falta del docen...",NaN
1,Prof. en Educación Inicial,2024.0,1º año,4.0,0,Secundario Incompleto,Primario Completo,2023,Pública,No,...,"Celular, Computadora portatil (Notebook/netbook)",De uso personal,"Red celular (datos), Wi-Fi","Hogar, Escuela/Instituto",Regular,Tal vez,Si,"De organización familiar, De transporte, Econó...","el orden,la organización sobre las aulas, ya q...",no
2,Prof. en Educación Inicial,2024.0,1º año,1.0,0,Ns/Nc,Ns/Nc,2017,Pública,Sí,...,Celular,De uso personal,Red celular (datos),Ninguno,Regular,Sí,No,NaN,.,.
3,Prof. en Educación Inicial,2024.0,NaN,7.0,0,Secundario Incompleto,Secundario Completo,2022,Pública,Sí,...,Celular,De uso personal,"Red celular (datos), Wi-Fi",Hogar,Regular,Sí,No,NaN,NaN,NaN
4,Prof. en Educación Inicial,2024.0,1º año,3.0,1,Secundario Incompleto,Secundario Incompleto,2022,Pública,No,...,Celular,De uso personal,"Red celular (datos), Wi-Fi","Hogar, Escuela/Instituto, Espacio público",Regular,Sí,No,NaN,"A mí punto de vista,cambiar el horario de ingr...","Con respecto al anexo,no hay alguna pregunta,y..."
5,Prof. en Educación Inicial,2024.0,1º año,4.0,0,Universitario Incompleto,Terciario Completo,2023,Pública,No,...,"Celular, Computadora portatil (Notebook/netbook)",De uso personal,Wi-Fi,Hogar,Buena,Sí,No,NaN,Que los horarios están mal distribuidos y con ...,La conectividad en el instituto no nos es otor...
6,Prof. en Educación Inicial,2024.0,1º año,9.0,1,Primario Completo,Primario Completo,2018,Pública,No,...,Celular,De uso personal,Wi-Fi,Hogar,Regular,Sí,No,NaN,NaN,NaN
7,Prof. en Educación Inicial,2024.0,1º año,3.0,0,Primario Completo,Secundario Incompleto,2022,Pública,No,...,Celular,De uso personal,"Red celular (datos), Wi-Fi","Hogar, Escuela/Instituto, Espacio público",Buena,Sí,No,NaN,El principal problema sería que esta encuesta ...,"Si existe la posibilidad de las clases online,..."
8,Prof. en Educación Inicial,2014.0,4º año,4.0,0,Primario Completo,Primario Completo,2013,Pública,No,...,Celular,De uso personal,Wi-Fi,Hogar,Buena,No,Si,Para trabajar / conseguir trabajo,Tardan en conseguir docentes reemplazantes,No
9,Prof. en Educación Inicial,2024.0,1º año,3.0,0,Primario Completo,Secundario Completo,2012,Pública,Sí,...,"Celular, Computadora portatil (Notebook/netbook)",De uso personal,Wi-Fi,Hogar,Buena,Sí,No,NaN,Este año la única dificultad que encuentro es ...,"Por el momento no deseo agregar nada más, solo..."

In [ ]:
df2["Cursaste_Otra_Carrera"].value_counts()

Cursaste_Otra_Carrera
No    141
Sí     73
Name: count, dtype: int64

In [ ]:
print("Moda año curricular",df2["Ano_Curricular"].mode())
print("Moda Miembros_Hogar",df2["Miembros_Hogar"].mode())
print("Moda Cantidad_Hijos",df2["Cantidad_Hijos"].mode())
print("Moda Carreras_Inscripcion",df2["Carreras_Inscripcion"].mode())
print("Moda Nivel_Educativo_Padre",df2["Nivel_Educativo_Padre"].mode())
print("Moda Nivel_Educativo_Madre",df2["Nivel_Educativo_Madre"].mode())

Moda año curricular 0    1º año
Name: Ano_Curricular, dtype: object
Moda Miembros_Hogar 0    4.0
Name: Miembros_Hogar, dtype: float64
Moda Cantidad_Hijos 0    0
Name: Cantidad_Hijos, dtype: object
Moda Carreras_Inscripcion 0    Prof. en Educación Inicial
Name: Carreras_Inscripcion, dtype: object
Moda Nivel_Educativo_Padre 0    Secundario Completo
Name: Nivel_Educativo_Padre, dtype: object
Moda Nivel_Educativo_Madre 0    Secundario Completo
Name: Nivel_Educativo_Madre, dtype: object

In [ ]:
df2["Carreras_Inscripcion"] = df2["Carreras_Inscripcion"].fillna("Prof. en Educación Inicial")
df2["Ano_Curricular"] = df2["Ano_Curricular"].fillna("1º año")
df2["Miembros_Hogar"] = df2["Miembros_Hogar"].fillna(4.0)
df2["Cantidad_Hijos"] = df2["Cantidad_Hijos"].fillna(0)
df2["Nivel_Educativo_Padre"] = df2["Nivel_Educativo_Padre"].fillna("Secundario Completo")
df2["Nivel_Educativo_Madre"] = df2["Nivel_Educativo_Madre"].fillna("Secundario Completo")
df2["Dificultades_Turno_Matutino"] = df2["Dificultades_Turno_Matutino"].fillna("No aclara")
df2["Problemas_Aspectos_Institucion"] = df2["Problemas_Aspectos_Institucion"].fillna("No aclara")
df2["Sugerencias_Encuesta"] = df2["Sugerencias_Encuesta"].fillna("No aclara")

In [ ]:
df2.loc[df2["Cursaste_Otra_Carrera"] == "Sí", "Carrera_Previa"]
cursaste_si = df2.loc[df2["Cursaste_Otra_Carrera"] == "Sí", "Carrera_Previa"]


df2.loc[df2["Cursaste_Otra_Carrera"] == "Sí", "Carrera_Previa"] = df2.loc[df2["Cursaste_Otra_Carrera"] == "Sí", "Carrera_Previa"].fillna("No aclara")

In [ ]:
df2["Carrera_Previa"] = df2["Carrera_Previa"].fillna("Sin carrera previa")

In [ ]:
df2.loc[df2["Cursaste_Otra_Carrera"] == "Sí", "Institucion_Estudio"] = df2.loc[df2["Cursaste_Otra_Carrera"] == "Sí", "Institucion_Estudio"].fillna("No aclara")
df2["Institucion_Estudio"] = df2["Institucion_Estudio"].fillna("Sin carrera previa")

In [ ]:
df2.loc[df2["Cursaste_Otra_Carrera"] == "Sí", "Estudios_Completados"] = df2.loc[df2["Cursaste_Otra_Carrera"] == "Sí","Estudios_Completados"].fillna("No aclara")
df2["Estudios_Completados"] = df2["Estudios_Completados"].fillna("Sin carrera previa")

In [ ]:
df2[["Cursaste_Otra_Carrera","Carrera_Previa","Institucion_Estudio","Estudios_Completados"]]

,Cursaste_Otra_Carrera,Carrera_Previa,Institucion_Estudio,Estudios_Completados
0,No,Sin carrera previa,Sin carrera previa,Sin carrera previa
1,No,Sin carrera previa,Sin carrera previa,Sin carrera previa
2,Sí,Profesorado de biología,Isp6,No
3,Sí,Tec. En Higiene y Seguridad,UNL,No
4,No,Sin carrera previa,Sin carrera previa,Sin carrera previa
...,...,...,...,...
209,No,Sin carrera previa,Sin carrera previa,Sin carrera previa
210,Sí,Ingeniería civil,FCEIA UNR,No
211,No,Sin carrera previa,Sin carrera previa,Sin carrera previa
212,Sí,Psicología,Facultad católica de santa fe,No
213,Sí,No aclara,No aclara,No

In [ ]:
df2["Problemas_Aspectos_Institucion"] = df2["Problemas_Aspectos_Institucion"].replace(".", "No aclara")

In [ ]:
df2["Sugerencias_Encuesta"] = df2["Sugerencias_Encuesta"].replace(".","No aclara")

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Carreras_Inscripcion            214 non-null    object
 1   Ano_Ingreso_Carrera             213 non-null    float64
 2   Ano_Curricular                  214 non-null    object
 3   Miembros_Hogar                  214 non-null    float64
 4   Cantidad_Hijos                  214 non-null    object
 5   Nivel_Educativo_Padre           214 non-null    object
 6   Nivel_Educativo_Madre           214 non-null    object
 7   Ano_Egreso_Secundaria           214 non-null    int64
 8   Gestion_Escuela                 214 non-null    object
 9   Cursaste_Otra_Carrera           214 non-null    object
 10  Carrera_Previa                  214 non-null    object
 11  Institucion_Estudio             214 non-null    object
 12  Estudios_Completados            214 non-null    object
 13  Medios_Tecnologicos_Estudios    214 non-null    object
 14  Dispositivos_Usados             214 non-null    object
 15  Conectividad                    214 non-null    object
 16  Conexión_Wifi                   214 non-null    object
 17  Calidad_Conexion                214 non-null    object
 18  Cursar_Mañana                   214 non-null    object
 19  Modificacion_Horario_Instituto  214 non-null    object
 20  Dificultades_Turno_Matutino     214 non-null    object
 21  Problemas_Aspectos_Institucion  214 non-null    object
 22  Sugerencias_Encuesta            214 non-null    object
dtypes: float64(2), int64(1), object(20)
memory usage: 38.6+ KB

In [ ]:
df2.to_csv("encuestaP2.csv",index=False)

# Union de df1 y df2 y exportacion de datos

In [ ]:
df2.head()

,Carreras_Inscripcion,Ano_Ingreso_Carrera,Ano_Curricular,Miembros_Hogar,Cantidad_Hijos,Nivel_Educativo_Padre,Nivel_Educativo_Madre,Ano_Egreso_Secundaria,Gestion_Escuela,Cursaste_Otra_Carrera,...,Medios_Tecnologicos_Estudios,Dispositivos_Usados,Conectividad,Conexión_Wifi,Calidad_Conexion,Cursar_Mañana,Modificacion_Horario_Instituto,Dificultades_Turno_Matutino,Problemas_Aspectos_Institucion,Sugerencias_Encuesta
0,Prof. en Educación Inicial,2022.0,3º año,2.0,1,Primario Incompleto,Terciario Completo,2015,Pública,No,...,Celular,De uso personal,Wi-Fi,Hogar,Buena,No,Si,Para trabajar / conseguir trabajo,"Si, avisar con anticipación la falta del docen...",No aclara
1,Prof. en Educación Inicial,2024.0,1º año,4.0,0,Secundario Incompleto,Primario Completo,2023,Pública,No,...,"Celular, Computadora portatil (Notebook/netbook)",De uso personal,"Red celular (datos), Wi-Fi","Hogar, Escuela/Instituto",Regular,Tal vez,Si,"De organización familiar, De transporte, Econó...","el orden,la organización sobre las aulas, ya q...",no
2,Prof. en Educación Inicial,2024.0,1º año,1.0,0,Ns/Nc,Ns/Nc,2017,Pública,Sí,...,Celular,De uso personal,Red celular (datos),Ninguno,Regular,Sí,No,No aclara,No aclara,No aclara
3,Prof. en Educación Inicial,2024.0,1º año,7.0,0,Secundario Incompleto,Secundario Completo,2022,Pública,Sí,...,Celular,De uso personal,"Red celular (datos), Wi-Fi",Hogar,Regular,Sí,No,No aclara,No aclara,No aclara
4,Prof. en Educación Inicial,2024.0,1º año,3.0,1,Secundario Incompleto,Secundario Incompleto,2022,Pública,No,...,Celular,De uso personal,"Red celular (datos), Wi-Fi","Hogar, Escuela/Instituto, Espacio público",Regular,Sí,No,No aclara,"A mí punto de vista,cambiar el horario de ingr...","Con respecto al anexo,no hay alguna pregunta,y..."

In [ ]:
df1.head()

,Marca_Temporal,Genero_Nacer,Autopercepcion,Nacionalidad,Indigena_O_Descendiente,Edad,Estado_Civil,Localidad_Residencia,Actividad_Fisica,Condiciones_Limitaciones,...,Medio_Transporte,Tiempo_Traslado,Financiamiento_Movilidad,Trabajas,Desempeno_Laboral,Actividad_Profesional,Obra_Social_Trabajo,Horas_Trabajo,Horarios_Trabajo,Beca_Estudios
0,2024-05-29 09:34:28.466,Mujer / Femenino,Mujer,Argentino/a,No,27.0,Soltero/a,Barrancas,No,No,...,Colectivo,Entre 30 minutos y 1 hora,Boleto Educativo Gratuito,Sí,Empleado en relación de dependencia,Empleada doméstica,No,de 10 a 20 hs semanales,Fijos,PROGRESAR
1,2024-05-29 09:35:20.150,Mujer / Femenino,Mujer,Argentino/a,No,18.0,Soltero/a,Larrechea,No,No,...,Auto,Menos de 30 minutos,Ingresos propios,No,No trabaja,No trabaja,No trabaja,No trabaja,No trabaja,PROGRESAR
2,2024-05-29 09:38:48.713,Mujer / Femenino,Mujer,Argentino/a,No,20.0,Soltero/a,Caima,"Sí, al menos una vez por semana",No,...,Colectivo,Entre 1 y 2 horas,Boleto Educativo Gratuito,No,No trabaja,No trabaja,No trabaja,No trabaja,No trabaja,PROGRESAR
3,2024-05-29 09:41:36.380,Mujer / Femenino,Mujer,Argentino/a,No,18.0,No aclara,Sauce Viejo,"Sí, al menos una vez por semana",No,...,Colectivo,Menos de 30 minutos,Boleto Educativo Gratuito,No,No trabaja,No trabaja,No trabaja,No trabaja,No trabaja,No cuento con ninguna beca
4,2024-05-29 09:46:56.746,Mujer / Femenino,Mujer,Argentino/a,No,21.0,En pareja/Unión de hecho,Coronda,No,No,...,Caminando,Menos de 30 minutos,No tengo gastos de movilidad,No,No trabaja,No trabaja,No trabaja,No trabaja,No trabaja,PROGRESAR

In [ ]:
df_combined = pd.concat([df1, df2], axis=1)
df_combined.to_csv("encuestra_procesada.csv",index=False)

In [ ]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 45 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Marca_Temporal                  214 non-null    object
 1   Genero_Nacer                    214 non-null    object
 2   Autopercepcion                  214 non-null    object
 3   Nacionalidad                    214 non-null    object
 4   Indigena_O_Descendiente         214 non-null    object
 5   Edad                            214 non-null    float64
 6   Estado_Civil                    214 non-null    object
 7   Localidad_Residencia            214 non-null    object
 8   Actividad_Fisica                214 non-null    object
 9   Condiciones_Limitaciones        214 non-null    object
 10  Afecciones_Mentales             214 non-null    object
 11  Distancia_Instituto             214 non-null    object
 12  Medio_Transporte                214 non-null    object
 13  Tiempo_Traslado                 214 non-null    object
 14  Financiamiento_Movilidad        214 non-null    object
 15  Trabajas                        214 non-null    object
 16  Desempeno_Laboral               214 non-null    object
 17  Actividad_Profesional           214 non-null    object
 18  Obra_Social_Trabajo             214 non-null    object
 19  Horas_Trabajo                   214 non-null    object
 20  Horarios_Trabajo                214 non-null    object
 21  Beca_Estudios                   214 non-null    object
 22  Carreras_Inscripcion            214 non-null    object
 23  Ano_Ingreso_Carrera             213 non-null    float64
 24  Ano_Curricular                  214 non-null    object
 25  Miembros_Hogar                  214 non-null    float64
 26  Cantidad_Hijos                  214 non-null    object
 27  Nivel_Educativo_Padre           214 non-null    object
 28  Nivel_Educativo_Madre           214 non-null    object
 29  Ano_Egreso_Secundaria           214 non-null    int64
 30  Gestion_Escuela                 214 non-null    object
 31  Cursaste_Otra_Carrera           214 non-null    object
 32  Carrera_Previa                  214 non-null    object
 33  Institucion_Estudio             214 non-null    object
 34  Estudios_Completados            214 non-null    object
 35  Medios_Tecnologicos_Estudios    214 non-null    object
 36  Dispositivos_Usados             214 non-null    object
 37  Conectividad                    214 non-null    object
 38  Conexión_Wifi                   214 non-null    object
 39  Calidad_Conexion                214 non-null    object
 40  Cursar_Mañana                   214 non-null    object
 41  Modificacion_Horario_Instituto  214 non-null    object
 42  Dificultades_Turno_Matutino     214 non-null    object
 43  Problemas_Aspectos_Institucion  214 non-null    object
 44  Sugerencias_Encuesta            214 non-null    object
dtypes: float64(3), int64(1), object(41)
memory usage: 75.4+ KB

In [ ]:
df_combined.head()

,Marca_Temporal,Genero_Nacer,Autopercepcion,Nacionalidad,Indigena_O_Descendiente,Edad,Estado_Civil,Localidad_Residencia,Actividad_Fisica,Condiciones_Limitaciones,...,Medios_Tecnologicos_Estudios,Dispositivos_Usados,Conectividad,Conexión_Wifi,Calidad_Conexion,Cursar_Mañana,Modificacion_Horario_Instituto,Dificultades_Turno_Matutino,Problemas_Aspectos_Institucion,Sugerencias_Encuesta
0,2024-05-29 09:34:28.466,Mujer / Femenino,Mujer,Argentino/a,No,27.0,Soltero/a,Barrancas,No,No,...,Celular,De uso personal,Wi-Fi,Hogar,Buena,No,Si,Para trabajar / conseguir trabajo,"Si, avisar con anticipación la falta del docen...",No aclara
1,2024-05-29 09:35:20.150,Mujer / Femenino,Mujer,Argentino/a,No,18.0,Soltero/a,Larrechea,No,No,...,"Celular, Computadora portatil (Notebook/netbook)",De uso personal,"Red celular (datos), Wi-Fi","Hogar, Escuela/Instituto",Regular,Tal vez,Si,"De organización familiar, De transporte, Econó...","el orden,la organización sobre las aulas, ya q...",no
2,2024-05-29 09:38:48.713,Mujer / Femenino,Mujer,Argentino/a,No,20.0,Soltero/a,Caima,"Sí, al menos una vez por semana",No,...,Celular,De uso personal,Red celular (datos),Ninguno,Regular,Sí,No,No aclara,No aclara,No aclara
3,2024-05-29 09:41:36.380,Mujer / Femenino,Mujer,Argentino/a,No,18.0,No aclara,Sauce Viejo,"Sí, al menos una vez por semana",No,...,Celular,De uso personal,"Red celular (datos), Wi-Fi",Hogar,Regular,Sí,No,No aclara,No aclara,No aclara
4,2024-05-29 09:46:56.746,Mujer / Femenino,Mujer,Argentino/a,No,21.0,En pareja/Unión de hecho,Coronda,No,No,...,Celular,De uso personal,"Red celular (datos), Wi-Fi","Hogar, Escuela/Instituto, Espacio público",Regular,Sí,No,No aclara,"A mí punto de vista,cambiar el horario de ingr...","Con respecto al anexo,no hay alguna pregunta,y..."